name: build macos arm64

on: workflow_dispatch

jobs:
  release:
    name: build macos arm64
    runs-on: macos-13-xlarge

    steps:
      - name: run shell scripts
        run: sh macos-build-script.sh
     
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: arm64
          path: dist/Real-ESRGAN\ GUI.app
